version: "4"

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://dpg-d64r2na4d50c73emdsu0-a.oregon-postgres.render.com:5432/postgres_uf83?sslmode=require
      KC_DB_USERNAME: postgres_uf83_user
      KC_DB_PASSWORD: ULYfTl4ag6rCZ8kInsyp70hTbmoVsSz0

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - "8181:8080"

    volumes:
      - ./docker/keycloak/realms:/opt/keycloak/data/import
