version: "3.8"

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]

    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://ep-bold-voice-algmzksr.c-3.eu-central-1.pg.koyeb.app:5432/koyebdb?sslmode=require
      KC_DB_USERNAME: koyeb-adm
      KC_DB_PASSWORD: npg_Bjvf7OepPG3S

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    ports:
      - "8181:8080"

    volumes:
      - ./docker/keycloak/realms:/opt/keycloak/data/import
