server {
    listen 80;
    server_name novel-tool-kit.id.vn;
    client_max_body_size 10M;
    resolver 127.0.0.11 valid=10s;

    location /api/ {
        set $upstream_api http://api-gateway:9000;
        proxy_pass $upstream_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    location / {
        set $upstream_keycloak http://keycloak:8080;
        proxy_pass $upstream_keycloak;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}