server:
  port: 8085
spring:
  application:
    name: transaction-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/online-stories-realm}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: ${VN_PAY_TMN_CODE}
    secretKey: ${VN_PAY_SECRET_KEY}
    returnUrl: http://localhost:8085/api/transactions/vn-pay-call-back
    version: 2.1.0
    command: pay
    orderType: other
  momo:
    partner-code: ${MOMO_PARTNER_CODE}
    access-key: ${MOMO_ACCESS_KEY}
    secret-key: ${MOMO_SECRET_KEY}
    endpoint: https://test-payment.momo.vn/v2/gateway/api/create
