server:
  port: 9000

spring:
    application:
        name: api-gateway
    threads:
      virtual:
        enabled: true
    security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://localhost:8181/realms/online-stories-realm
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        server:
          webmvc:
            routes:
              - id: user-service
                uri: lb://user-service
                predicates:
                  - Path=/api/users/**
              - id: auth-service
                uri: lb://authentication-service
                predicates:
                  - Path=/api/auth/**
              - id: story-service
                uri: lb://story-service
                predicates:
                  - Path=/api/stories/**
              - id: media-service
                uri: lb://media-service
                predicates:
                  - Path=/api/media/**
              - id: trans-service
                uri: lb://transaction-service
                predicates:
                  - Path=/api/transactions/**
              - id: recommend-service
                uri: lb://recommend-service
                predicates:
                  - Path=/api/recommend/**
              - id: report-service
                uri: lb://report-service
                predicates:
                  - Path=/api/reports/**
              - id : ai-service
                uri: lb://ai-service
                predicates:
                  - Path=/api/ai/**
#              - id : social-service
#                uri: http://localhost:8089
#                predicates:
#                  - Path=/api/social/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
