server:
  port: 8088
spring:
  application:
    name: ai-service
  ai:
    retry:
      max-attempts: 1
    vectorstore:
      opensearch:
        uris: ${OPENSEARCH_URL}
        index-name: story_chunks_vector
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        project-id: ${GEMINI_PROJECT_ID}
        chat:
          options:
            model: gemini-3.1-flash-lite
        embedding:
          api-key: ${GEMINI_API_KEY}
          project-id: ${GEMINI_PROJECT_ID}
          text:
            options:
              model: gemini-embedding-001
  #    openai:
#      api-key: ${GEMINI_API_KEY}
#      chat:
#        base-url: https://generativelanguage.googleapis.com
#        completions-path: /v1beta/openai/chat/completions
#        options:
#          model: gemini-3.1-flash-lite-preview
#      embedding:
#        base-url: https://generativelanguage.googleapis.com
#        embeddings-path: /v1beta/openai/embeddings
#        options:
#          model: gemini-embedding-001
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/online-stories-realm}

bonsai:
  opensearch:
    url: ${OPENSEARCH_URL}
siliconflow:
  api-key: ${SILICON_API_KEY}
api:
  endpoints:
    story: ${API_STORY_ENDPOINT:http://localhost:3000/story}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.ai: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka.clients.Metadata: ERROR
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: WARN