server:
  port: 8082

keycloak:
    server-url: "http://localhost:8181"
    realm: ${REALM}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false