server:
    port: 8081
spring:
    application:
        name: user-service
    data:
        mongodb:
            uri: ${MONGODB_URI}
            database: ${MONGODB_DB}
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/online-stories-realm}

keycloak:
    admin:
        server-url: "http://localhost:8181"
        realm: ${REALM}
        client-id: ${CLIENT_ID}
        client-secret: ${CLIENT_SECRET}

app:
    keycloak:
        realm: ${REALM}

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

logging:
    level:
        org.springframework.security: DEBUG