server:
    port: 8081
spring:
    application:
        name: user-service
    data:
        mongodb:
            uri: ${MONGODB_URI}
            database: ${MONGODB_DB}
        redis:
            url: ${REDIS_URL}
            ssl:
                enabled: true
            timeout: 5000
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 8
                    min-idle: 0
    kafka:
        bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            acks: all
            retries: 3
        consumer:
            group-id: ${spring.application.name}
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            auto-offset-reset: earliest
            properties:
                spring.json.trusted.packages: "*"

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/online-stories-realm}

keycloak:
    admin:
        server-url: "http://localhost:8181"
        realm: ${REALM}
        client-id: ${CLIENT_ID}
        client-secret: ${CLIENT_SECRET}

app:
    keycloak:
        realm: ${REALM}
        redirect-uri: ${KEYCLOAK_REDIRECT_URI:http://localhost:3000}

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/

logging:
    level:
        org.springframework.security: DEBUG
        org.apache.kafka.clients.NetworkClient: ERROR
        org.apache.kafka.clients.Metadata: ERROR
        org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: WARN