server:
  port: 8083
spring:
  application:
      name: story-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB}
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
#      enable-auto-commit: true
#      auto-commit-interval-ms: 1000
      properties:
        spring.json.trusted.packages: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/online-stories-realm}

azure:
  speech:
    key: ${AZURE_SPEECH_KEY}
    region: ${AZURE_SPEECH_REGION}

eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/