server:
  port: 8086
spring:
  application:
    name: recommend-service
  cache:
    type: redis
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DB}
    redis:
      url: ${REDIS_URL}
      ssl:
        enabled: true
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  elasticsearch:
    uris: ${ELASTICSEARCH_URIS}
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/online-stories-realm}

app:
  keycloak:
    realm: ${REALM}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

bonsai:
  opensearch:
    url: ${OPENSEARCH_URL}

#gemini:
#  api:
#    key: ${GEMINI_API_KEY}

cohere:
  api:
    key: ${COHERE_API_KEY}

logging:
  level:
    org.springframework.security: DEBUG
    org.apache.kafka.clients.NetworkClient: ERROR
    org.apache.kafka.clients.Metadata: ERROR
    org.apache.kafka.clients.consumer.internals.ConsumerCoordinator: WARN